export { tooltipVariation, popperVariation, withContextMenuVariation } from './defaults';
export {
  CreateOptions,
  FloatingInstance,
  FloatingProps,
  ExtendedFloatingProps,
  FloatingElement,
  ExtendedFloatingInstance,
  FloatingConfig,
  FloatingContent,
  FloatingLoader,
  FLOATING_LOADER,
  FLOATING_CONFIG,
  FLOATING_LOADER_COMPONENT,
  FLOATING_LOADER_TIMING,
  FloatingLoaderTiming,
  // Deprecated aliases
  TippyInstance,
  TippyProps,
  ExtendedTippyProps,
  TippyElement,
  ExtendedTippyInstance,
  TippyConfig,
  TippyContent,
  TippyLoader,
  TIPPY_LOADER,
  TIPPY_CONFIG,
  TIPPY_LOADER_COMPONENT,
  TIPPY_LOADER_TIMING,
  TippyLoaderTiming,
} from './floating.types';
export {
  provideFloatingLoader,
  provideFloatingConfig,
  withFloatingLoaderComponent,
  withFloatingLoaderTiming,
  // Deprecated aliases
  provideTippyLoader,
  provideTippyConfig,
  withTippyLoaderComponent,
  withTippyLoaderTiming,
} from './providers';
