name: '@ngneat/helipopper'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - uses: actions/cache@v5
        with:
          path: ~/.cache/Cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: cypress-binary-${{ runner.os }}-

      - run: pnpm install --frozen-lockfile
        env:
          HUSKY: '0'

      - run: pnpm exec cypress install

      - name: Build playground app in production mode
        run: pnpm build:playground

      - uses: cypress-io/github-action@v7
        with:
          browser: chrome
          install: false
          start: pnpm serve:playground:static
          wait-on: http://localhost:4200

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
        env:
          HUSKY: '0'

      - name: Build library
        run: pnpm build:lib
