name: '@ngneat/helipopper'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Npm install
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
        env:
          HUSKY_SKIP_INSTALL: 'true'
      - run: npm i

      - name: Build playground app in production mode
        run: npm run build:playground

      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run serve:playground:static
          wait-on: http://localhost:4200

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Npm install
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
        env:
          HUSKY_SKIP_INSTALL: 'true'
      - run: npm i

      - name: Build library
        run: npm run build:lib

      - name: Build playground
        run: npm run build
